### ISSUE TITLE
Tag 0.5.4 doesn't have a setup.py

### ISSUE THREAD

**Issue by frankcash** [epoch8/airflow-exporter#53]
Can you please tag a 1.10.2 safe version that has a setup.py to allow pip install i.e.

### Command
```
✗ pip install --verbose git+git://github.com/epoch8/airflow-exporter.git@v0.5.4
```

### Throws an error

```
Created temporary directory: /private/var/folders/7v/7q7v2wtd7nz3b8g_0d4fbt980000gp/T/pip-ephem-wheel-cache-7szgnebb
Created temporary directory: /private/var/folders/7v/7q7v2wtd7nz3b8g_0d4fbt980000gp/T/pip-req-tracker-h7n0vflg
Created requirements tracker '/private/var/folders/7v/7q7v2wtd7nz3b8g_0d4fbt980000gp/T/pip-req-tracker-h7n0vflg'
Created temporary directory: /private/var/folders/7v/7q7v2wtd7nz3b8g_0d4fbt980000gp/T/pip-install-md5gak29
Collecting git+git://github.com/epoch8/airflow-exporter.git@v0.5.4
  Created temporary directory: /private/var/folders/7v/7q7v2wtd7nz3b8g_0d4fbt980000gp/T/pip-req-build-mvlzmuh0
  Cloning git://github.com/epoch8/airflow-exporter.git (to revision v0.5.4) to /private/var/folders/7v/7q7v2wtd7nz3b8g_0d4fbt980000gp/T/pip-req-build-mvlzmuh0
  Running command git clone -q git://github.com/epoch8/airflow-exporter.git /private/var/folders/7v/7q7v2wtd7nz3b8g_0d4fbt980000gp/T/pip-req-build-mvlzmuh0
  Running command git show-ref v0.5.4
  b39c345a57765d768777da60ffe9ded69f0d4e3d refs/tags/v0.5.4
  Running command git rev-parse HEAD
  ebaf76348f1bf0e47c9b22b534342428da57e3bb
  Running command git checkout -q b39c345a57765d768777da60ffe9ded69f0d4e3d
  Added git+git://github.com/epoch8/airflow-exporter.git@v0.5.4 to build tracker '/private/var/folders/7v/7q7v2wtd7nz3b8g_0d4fbt980000gp/T/pip-req-tracker-h7n0vflg'
    Running setup.py (path:/private/var/folders/7v/7q7v2wtd7nz3b8g_0d4fbt980000gp/T/pip-req-build-mvlzmuh0/setup.py) egg_info for package from git+git://github.com/epoch8/airflow-exporter.git@v0.5.4
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/ccash3/Code/frankcash/airflow_compose/venv/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/7v/7q7v2wtd7nz3b8g_0d4fbt980000gp/T/pip-req-build-mvlzmuh0/setup.py'
Cleaning up...
  Removing source in /private/var/folders/7v/7q7v2wtd7nz3b8g_0d4fbt980000gp/T/pip-req-build-mvlzmuh0
Removed git+git://github.com/epoch8/airflow-exporter.git@v0.5.4 from build tracker '/private/var/folders/7v/7q7v2wtd7nz3b8g_0d4fbt980000gp/T/pip-req-tracker-h7n0vflg'
```

When I download the `.zip` from the release and run `ls -la` there is no `setup.py`.  I see on the master branch it was introduced for `v1.0`, but that doesn't support `1.10.2`

**Comment by alannesta** [comment]
For `0.5.4`, you could directly copy the file `prometheus_exporter.py` to the plugins folder of your airflow installation.

**Comment by frankcash** [comment]
Yes, I definitely understand that.  But, I wonder if you could back port the 1.10.2 support through pip as it would make use easier users of 1.10.2 airflow.

If you'd be open to creating a branch and then accepting a PR for it that could be helpful too.

**Comment by theadityapathak** [comment]
How to install airflow-exporter in airflow version 1.9.0?

**Comment by elephantum** [comment]
Closing as stale
