### ISSUE TITLE
container 

### ISSUE THREAD

**Issue by continuum-akshay-jadhav** [epoch8/airflow-exporter#64]
Hi Team,

I have used PIP install in my Airflow container and tried to view metrics at IP:port/admin/metrics but i am getting below error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow_prometheus_exporter/prometheus_exporter.py", line 377, in index
    return Response(generate_latest(), mimetype='text/plain')
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/exposition.py", line 90, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 75, in collect
    for metric in collector.collect():
  File "/usr/local/lib/python3.6/site-packages/airflow_prometheus_exporter/prometheus_exporter.py", line 285, in collect
    task_duration.add_metric(
AttributeError: 'float' object has no attribute 'add_metric'
.

Can you please help me with this?

Thanks.

**Comment by elephantum** [comment]
@continuum-akshay-jadhav you installed different package (seems that it’s a fork with modifications). 

Package that we support is called `airflow_exporter`. Not `airflow_prometheus_exporter`
