### ISSUE TITLE
Not compatible with 2.0.0

### ISSUE THREAD

**Issue by mengleihouzz** [epoch8/airflow-exporter#88]
current airflow exporter does not compatible with 2.0.0.

`[2021-01-21 11:00:32,756] {plugins_manager.py:199} ERROR - Failed to import plugin AirflowPrometheus
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airflow/plugins_manager.py", line 189, in load_entrypoint_plugins
    plugin_class = entry_point.load()
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/airflow_exporter/prometheus_exporter.py", line 152, in <module>
    if settings.RBAC:
AttributeError: module 'airflow.settings' has no attribute 'RBAC'
`

Do we have plan to support that?

**Comment by elephantum** [comment]
Yes, we’d like to support that. I’ll take a look on weekend.

**Comment by mengleihouzz** [comment]
@elephantum any updates regarding this?

**Comment by gaurav1008** [comment]
+1 Observed same. Any WA available?

**Comment by dimon222** [comment]
I've tried to implement potential hotfix in #89  and hoping someone can verify.

**Comment by elephantum** [comment]
Hi, everyone, can you please try version from `airflow2` branch? It is not yet packaged, because CI-tests are broken, but I feel that it should work fine.

**Comment by elephantum** [comment]
Work in progress PR is here: https://github.com/epoch8/airflow-exporter/pull/90

**Comment by elephantum** [comment]
Fixed in https://github.com/epoch8/airflow-exporter/pull/90
